variable "region" {
  description = "The AWS region where resources will be created"
  default     = "us-east-1"
}
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.94.1"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "4.1.0"
    }
  }
  backend "s3" {
    bucket       = "my-tf-state-3y5"
    key          = "terraform/default-state"
    region       = "ap-south-1"
    use_lockfile = true
  }
}

# Configure the AWS Provider
provider "aws" {
  region = var.region
  default_tags {
    tags = {
      "managed_by" = "terraform",
      "region"     = var.region,
      "project"    = "tls-example"
    }
  }
}

# RSA key of size 4096 bits
resource "tls_private_key" "rsa-4096-example" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

output "private_key" {
  value = nonsensitive(tls_private_key.rsa-4096-example.private_key_pem)
}

output "public_key" {
  value = nonsensitive(tls_private_key.rsa-4096-example.private_key_pem)
}

resource "aws_secretsmanager_secret" "private_key_secret" {
  name                    = "tls-example-private-key"
  description             = "Private key generated by tls_private_key.rsa-4096-example"
  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "private_key_secret_version" {
  secret_id     = aws_secretsmanager_secret.private_key_secret.id
  secret_string = tls_private_key.rsa-4096-example.private_key_pem
}
